### ISSUE TITLE
Add Ticket Type

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-turnstile#55]
Ticket types are things like `vip`, `early entry`, etc. 

Right now there are no ways of creating these, but I don't want them to be necessarily static. With such, there should be a relation that allows a `TicketType[]` to be associated with an `Event`. This is better thought of as a list of types of `TicketTypes` that a checkin in the event can have.

Finally, we need to be able to add this ticket type on the purchase page.

```[tasklist]
### Tasks
- [x] Update Prisma to have a Ticket Type
- [x] Add ticket type field to purchase page
- [x] Add sample data and test
```
